### ISSUE TITLE
Break of drag some points

### ISSUE THREAD

**Issue by asmyasnikov** [chrispahm/chartjs-plugin-dragData#10]
Hi!
How to break of drogging some points? I tried throwing exception on onDragStart callback for cancelling dragging of interest points, but this not working =(
Any ways?

**Comment by chrispahm** [comment]
Hey there,

if I get your question right, you want to prohibit dragging of some points, right?
I build a (somewhat) [hacky solution as a fiddle](https://jsfiddle.net/87f6w1aq/1/) that shows how you could achieve this.
I realised that the README does not point out that the `onDragStart` callback takes two arguments `event, element` (instead of only event), where element is the ChartJS element that was clicked.

Essentially, I checked if the clicked element is the one we would like to prohibit, store its original value, and keep updating the point with its original value during drag.

Hope this is what you were aiming for?
Best, Christoph

**Comment by asmyasnikov** [comment]
Tnx! =)
This solution are satis for me)

**Comment by eddie-atkinson** [comment]
Hey @chrispahm,

I have a slightly more advanced use case than above. I am using Vue and have multiple charts rendered on a single page. Ideally I would like some of the points on each of the charts to be disabled whilst the overs remain draggable. I've tried without success to use the approach above, would you mind taking a look?

https://codepen.io/pen/?template=abBEbNB

**Comment by eddie-atkinson** [comment]
Never mind, found the answer I needed in the docs:

>To avoid dragging specific data points inside a draggable dataset, you can return false to function onDragStart.

Thanks Chris for such an awesome library!
