### ISSUE TITLE
dragData for bubble chart

### ISSUE THREAD

**Issue by FlintMayers** [chrispahm/chartjs-plugin-dragData#3]
Awesome plugin. Works really well with line charts, however, I can't seem to make it work with bubble charts. Whenever the data point bubble is dragged it disappears.

**Comment by chrispahm** [comment]
Glad to hear that you like the plugin! 
For now, unfortunately only line charts are supported. With the bubble charts, I guess one would need to discuss the expected behavior while dragging first. Would you like to increase/decrease the Bubble’s size on mousemove up/down or rather shift it up/down/left/right. Probably a mix of left/right click mouse events?
Let me know what you think, then we can proceed.

**Comment by FlintMayers** [comment]
I had in mind a bubble that's draggable around onClick left/right/up/down.

Something similar to the following

https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#An%20Example:%20Implement%20Dragging

https://www.highcharts.com/products/plugin-registry/single/3/Draggable%20Points

**Comment by chrispahm** [comment]
Should be working with the newest release. See [the bubble chart example](https://chrispahm.github.io/chartjs-plugin-dragData/bubble.html).
