### ISSUE TITLE
Is react-chartjs-2 still supported?

### ISSUE THREAD

**Issue by StefanoSGI** [chrispahm/chartjs-plugin-dragdata#30]
Testing the React wrapper in your Fiddle: 
https://jsfiddle.net/rts082hj/
the dragging action doesn't work for me.

Confirmed also locally with `react-chartjs-2@2.7.6` and `chartjs-plugin-dragdata@1.0.1`

Thank you!

**Comment by chrispahm** [comment]
Hey there,
so the fiddle wasn't working because I recently had to rename the plugin to adhere to the official chartjs plugin guidelines (went from dragData to dragdata). The required plugin file in the fiddle wasn't found on the server and therefore it didn't work.
I just updated the filenames in the assets/dist folders, updated the [react fiddle](https://jsfiddle.net/3v9kexbh/) and pushed a new patch release (`v1.0.2`). Would be nice if you could confirm :)
Best
Christoph

**Comment by StefanoSGI** [comment]
Hi @chrispahm, thank you for looking into this. I confirm the Fiddle works.
