### ISSUE TITLE
'dragData' Not Recognized as Options Property in Angular

### ISSUE THREAD

**Issue by rkp8** [chrispahm/chartjs-plugin-dragdata#73]
**'dragData' Option Not Recognized:**

Using Chart.js 2.9.3 in Angular. Imported plugin: import 'chartjs-plugin-dragdata'
However, dragData is not recognized as a chart option.

Receiving the following error:
index.d.ts(278, 9): The expected type comes from property 'options' which is declared here on type 'ChartConfiguration'

Please let me know how to fix this issue.

**Comment by rkp8** [comment]
Screenshot: 
<img width="547" alt="Screenshot (63)" src="https://user-images.githubusercontent.com/60204834/128421383-255117bc-2a0a-4795-953e-7c1ab50b5511.png">

**Comment by chrispahm** [comment]
Hey @rkp8 👋 

I'm not a TypeScript expert, but I'd guess you need to extend the `ChartOptions` interface 
and use the extended interface instead of the original one when creating the chart instance.

```ts
interface ChartOptionsDragData extends ChartOptions {
  dragData: boolean;
  // ToDo: add the remaining properties auch as 'onDragStart' etc.
}
```

As this is more of a TypeScript related question rather than a bug in this plugin, I'd recommend you to ask this question on StackOverflow with the corresponding tags (e.g. `chart.js`, `plugin`, and `TypeScript`)

**Comment by chrispahm** [comment]
Just as a reference:
Here's a complete example using Angular (and presumably TypeScript)
https://plnkr.co/edit/s2aPrPExAmp8gnQc?open=lib%2Fapp.ts&deferRun=1&preview

**Comment by rkp8** [comment]
Hi Chris, 
I extended the chartOptions interface located in index.d.ts and it worked perfectly. Thank you so much.

**Comment by kemo89** [comment]
For chartjs version 3 I did this:
`export type MyChartOptions = ChartOptions & {
  plugins: {
    dragData: {
      round: number;
      showTooltip: boolean;
    };
  };
};`
